### PR TITLE
Add ArgonJsonConverterAdapter for adapting a Newtonsoft.Json.JsonConverter to Argon.JsonConverter

### PR DESCRIPTION
**Pull request by ldeluigi**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/VerifyTests/Verify.NewtonsoftJson?pullRequest=1) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/VerifyTests/Verify.NewtonsoftJson?pullRequest=1) before we can accept your contribution.<br/><br/>:x: ldeluigi [sign now](https://cla.dotnetfoundation.org/VerifyTests/Verify.NewtonsoftJson?pullRequest=1)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/VerifyTests/Verify.NewtonsoftJson?pullRequest=1) it.</sub>

**Comment by SimonCropp** [comment]
can u add some tests to ensure this works with scrubbers https://github.com/VerifyTests/Verify/blob/main/docs/scrubbers.md and ignoring members https://github.com/VerifyTests/Verify/blob/main/docs/serializer-settings.md#ignore-member-by-name

**Comment by SimonCropp** [comment]
and add some docs showing how people should use it

**Comment by ldeluigi** [comment]
@SimonCropp done

**Comment by SimonCropp** [comment]
can u change that test to use the generic variant of IgnoreMember. since that is the approach most people use

```
settings.IgnoreMember<IgnoreExplicitTarget>(_ => _.PropertyThatThrows);
```

**Comment by ldeluigi** [comment]
> can u change that test to use the generic variant of IgnoreMember. since that is the approach most people use
> 
> ```
> settings.IgnoreMember<IgnoreExplicitTarget>(_ => _.PropertyThatThrows);
> ```

it's not possible since I'm using VerifyJson. I'll make another test

**Comment by ldeluigi** [comment]
It seems to not be working with the generic version. I can't debug because you've put debugger skips

**Comment by SimonCropp** [comment]
>you've put debugger skips

not sure i understand?

**Comment by ldeluigi** [comment]
> > you've put debugger skips
> 
> not sure i understand?

it seems that if I try to F11 during debug into Verify(employee, settings) the debugger skips some method calls because there is a DebuggerStepThrough attribute and I can't understand what's happening

**Comment by SimonCropp** [comment]
i have not used DebuggerStepThrough anywhere in Verify

**Comment by ldeluigi** [comment]
> i have not used DebuggerStepThrough anywhere in Verify

Weird. I'll investigate deeper in my next free time. 🤔

**Comment by ldeluigi** [comment]
Ok I went deeper and I understood everything. Basically any adapter won't work with scrub/ignore members because it uses a different contract resolver. That's it. The best I can do is document that scrubbers and ignore members don't work.

**Comment by ldeluigi** [comment]
Otherwise we close the entire PR and I will implement a JsonConverter manually again for my classes in my projects

**Comment by ldeluigi** [comment]
I decided that this implementation does not meet the standards I was looking for. I'm concluding that reimplementing converters is the only possible right way to solve the issue. Thanks.

**Pull request closed without merging**
